//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "voice_lines"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i32,
    pub dialogue_id: i32,
    pub voice_name: String,
    pub voice_location: String,
    pub file_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    DialogueId,
    VoiceName,
    VoiceLocation,
    FileName,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Dialogue,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::DialogueId => ColumnType::Integer.def(),
            Self::VoiceName => ColumnType::Text.def(),
            Self::VoiceLocation => ColumnType::Text.def(),
            Self::FileName => ColumnType::Text.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Dialogue => Entity::belongs_to(super::dialogue::Entity)
                .from(Column::DialogueId)
                .to(super::dialogue::Column::Id)
                .into(),
        }
    }
}

impl Related<super::dialogue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dialogue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
