[package]
name = "st_application"
version = "0.1.0"
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
tracing.workspace = true
eyre.workspace = true

tokio = { workspace = true, features = ["full"] }
tokio-util.workspace = true

url = { version = "2.5.4", features = ["serde"] }

serde = { workspace = true, features = ["derive", "rc"] }

# Conf
config = { version = "0.15.6", features = ["toml"] }
platform-dirs = "0.3"
toml = "0.8"

# ML
st_system = {path = "../st_system"}
st_data = { path = "../st_data" }
st_audio = { path = "../st_audio" }
st_ml = { path = "../st_ml" }