[package]
name = "small_talk_whisper"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
whisper-rs = { git = "https://github.com/tazz4843/whisper-rs", features = []}
whisper-rs-sys = { git = "https://github.com/tazz4843/whisper-rs", features = []}