[package]
name = "st_system"
version = "0.1.0"
edition.workspace = true

[dependencies]
tracing.workspace = true
eyre.workspace = true
error_set.workspace = true
itertools = { workspace = true }

papaya = { version = "0.2.1", features = ["serde"] }
rand = "0.9.0"
strsim = "0.11.1"
bytemuck = "1.21.0"
regex = { version = "1.12", features = ["pattern"] }

tokio.workspace = true
tokio-util.workspace = true
futures = { version = "0.3" }
futures-lite = "2.6.0"

reqwest = { version = "0.12.9", features = ["json", "multipart"] }
url = { version = "2.5.4", features = ["serde"] }

schemars.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true

# Persistence
st_db = { path = "../st_db" }
sqlx = "0.8.5"
sea-orm.workspace = true
sea-query.workspace = true

# Path Walking
walkdir = "2"
path_abs = { version = "0.5", default-features = false }

# Conf
platform-dirs = "0.3"

st_data = { path = "../st_data" }
st_audio = { path = "../st_audio" }
wavers.workspace = true

# ML
st_ml = { path = "../st_ml", features = ["cuda"] }
bollard = "0.19.4"
process-wrap = { version = "9.0.0", features = ["tokio1"] }

[dev-dependencies]
tracing-test = "0.2.5"